### ISSUE TITLE
Call Getting Rejected Immediately

### ISSUE THREAD

**Issue by ralfisalhon** [voximplant/react-native-demo#24] opened 2018-07-23 10:36 UTC
Hello!

First of all, thank you for this demo. It has saved me a lot of time. This specific issue is without any changed code from the demo. I am having some trouble with initiating a call. I have two iOS simulators open on my computer, and I have logged in with different accounts on both. They are logged in to the same application, of course.

When initiating a call from a simulator, I can see the call screen appearing on the second simulator for a brief moment, before being greeted with an "Error 603", which I have found to be the error "Call was rejected" from https://voximplant.com/docs/references/websdk/voximplant/callevents#failed

Is this happening because I am running two instances of the application on my computer? I haven't had a similar problem before. (EDIT: Ran from two different computers, same problem)

When I call: https://puu.sh/B1BU2/17f9628a47.png
1 second after: https://puu.sh/B1BYe/5ca994c479.png (EDIT: link was broken)

Thank you!
- Ralfi

**Comment by YuliaGrigorieva** [comment] 2018-07-23 10:52
Hello!

Could you please check if you have this log message in your logs (Xcode output):
https://github.com/voximplant/react-native-demo/blob/61a61c3bfbef4becc2a37da3fa6e04f62a954aef/src/manager/CallManager.js#L65

Voximplant SDK supports multiple calls at the same time, however to simplify the demo we implemented the demo with the ability to have only one call at the same time. So in case if there is already an active call, and the client receives a new incoming call, it is rejected with the log message that I pointed above.

In case if you observe this message and you don't have an active call at the moment of new incoming call, please provide the steps to reproduce the issue, so we can investigate and fix it.

Best regards,
Yulia Grigorieva

**Comment by ralfisalhon** [comment] 2018-07-23 11:04
Hello Yulia,

Thanks for a fast response.

I do indeed have this in my console:

2018-07-23 14:00:32.570 [info][tid:com.facebook.react.JavaScript] CallManager: incomingCall: already have a call, rejecting new call, current call id 1eb2644fa6de6c28.1532343631.577753
2018-07-23 14:00:32.570249+0300 Hearo[75580:1344500] CallManager: incomingCall: already have a call, rejecting new call, current call id 1eb2644fa6de6c28.1532343631.577753

However, this is strange. I don't have an active call as far as I know.

**Comment by ralfisalhon** [comment] 2018-07-23 11:06
To reproduce the issue, simply run the demo application from two simulators, and attempt to call each other.

**Comment by YuliaGrigorieva** [comment] 2018-07-23 11:08
Hello!

Thank you for the details. I will try and will get back to you.

Best regards,
Yulia Grigorieva

**Comment by ralfisalhon** [comment] 2018-07-23 11:12
Hello Yulia,

I have temporarily solved the issue by commenting out line 66 from CallManager.js
This is the line that called event.call.decline(); if (this.call !== null)

Please let me know if this was a problem on my part!

Thanks again,
- Ralfi

**Comment by ralfisalhon** [comment] 2018-07-23 11:58
Hi Yulia,

An update on the problem: 
There seems to be 2 attempted calls.
Here is a picture to show what I mean:
<img width="1359" alt="screen shot 2018-07-23 at 2 56 39 pm" src="https://user-images.githubusercontent.com/16303372/43075206-b48d9734-8e88-11e8-9ab9-93db2a319011.png">

I hope this helps.
Also, if you have the time, I have one more question.
In my scenario, I am trying to record the call that is happening, but I have no luck. It always appears as a 0 seconds recording. Am I missing something?
<img width="798" alt="screen shot 2018-07-23 at 2 57 58 pm" src="https://user-images.githubusercontent.com/16303372/43075231-d0231906-8e88-11e8-898a-7cb2c1b4fcda.png">

Thanks!
- Ralfi

**Comment by YuliaGrigorieva** [comment] 2018-07-23 12:38
Hello!

Thank you for provided information.

It seems that the issue is caused by your scenario.

Please check docs for the "[forwardCallToUserDirect](https://voximplant.com/docs/references/voxengine/voxengine#forwardcalltouserdirect)", it's a syntax shortcut for accepting incoming call, making outgoing P2P call and connecting them. Your code below adds a second handler and initiate a second call, most probably not what you really want to achieve. It seems that demo receives 2 incoming calls and rejects the second one.

Regarding recording call issue, call record is not supported in P2P mode due to the media is not going through our servers.

So, to resolve your issue with 2 incoming calls, you need to use "forwardCallToUserDirect" method only OR remove the first line and use the rest part of your scenario,

To resolve the issue with call recording, you need to use "forwardCallToUser" method in your scenario. It would look something like:
```
VoxEngine.forwardCallToUser(function(call1,call2){
  call1.record({stereo:true,lossless:true,transcribe:true})
});
```

Best regards,
Yulia Grigorieva

**Comment by ralfisalhon** [comment] 2018-07-23 12:48
Hello again Yulia,

Thank you again for a quick reply.
I am still having problem with recording and transcribing the call. I am still trying to learn scenarios :)

This is my scenario:
<img width="798" alt="screen shot 2018-07-23 at 2 57 58 pm" src="https://user-images.githubusercontent.com/16303372/43077269-b2393b62-8e8f-11e8-8da9-b3e3cda5d50a.png">

This is my console:
<img width="1363" alt="screen shot 2018-07-23 at 3 46 47 pm" src="https://user-images.githubusercontent.com/16303372/43077275-b6838538-8e8f-11e8-883a-6b565bcee2e9.png">

As you can see, the call recorder still appears as 0 seconds.

Thank you for your time,
- Ralfi

**Comment by YuliaGrigorieva** [comment] 2018-07-23 13:14
Hello!

Your scenario is still making 2 calls, but now one call is in p2p mode and the second one - through our servers.


Please change your scenario to the following (i.e. completely remove your current scenario and add provided one):
```
VoxEngine.forwardCallToUser(function(call1,call2){
  call1.record({stereo:true,lossless:true,transcribe:true})
});
```

Please let me know the results.

Best regards,
Yulia Grigorieva

**Comment by YuliaGrigorieva** [comment] 2018-07-23 13:39
Great news!

I'm closing this issue for now, feel free to open a new one in case of any issues.

Best regards,
Yulia Grigorieva

**Closed by YuliaGrigorieva** 2018-07-23 13:39 UTC
